"""empty message

Revision ID: 37e727cc20bb
Revises: 619cda1cdc3f
Create Date: 2022-06-02 23:22:40.854858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e727cc20bb'
down_revision = '619cda1cdc3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.drop_column('venue', 'seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('venue', 'seeking_talent')
    # ### end Alembic commands ###
