"""empty message

Revision ID: 619cda1cdc3f
Revises: 
Create Date: 2022-06-02 23:02:50.057492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619cda1cdc3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
